### ISSUE TITLE
Simplier intervals

### ISSUE THREAD

**Issue by ai** [antyakushev/postcss-for#1]
``` css
@for $i from 1 to 3 {}
```

reproduces only `1` and `2`, becaus you copy JS `for` statement logic? Like `for ( i = 1; i < 3; i++ )`?

I think we should not copy bad design from JS. `@for $i from 1 to 3` should be more human and reproduses `1`, `2` and `3`.

It will also remove `through` keyword. And one keyword is always better.

/cc @antyakushev

**Comment by antyakushev** [comment]
@ai this copies sass syntax. So the change can be quite unexpected for the sass users, though I agree that it does look better.

**Comment by ai** [comment]
Right now there is no plugins, that copies Sass syntax 1-to-1.

So I think it is a good place to fix this bad design.

**Comment by antyakushev** [comment]
Ok, will do :smile:
