### ISSUE TITLE
Regression in 2.1.0

### ISSUE THREAD

**Issue by plesiecki** [antyakushev/postcss-for#16]
Hello, 

After updating to 2.1.0 I notice `postcss-for` fails to process this particular piece of custom css:

``` css
:root {
  @for $weight from 100 to 900 by 100 {
    --foo-$(weight): $weight;
  }
}
```

It fails for simpler case as well:

``` css
:root {
  @for $weight from 1 to 2 {
    --foo: $weight;
  }
}
```

I have `postcss-for` before `postcss-custom-properties` in my plugin list.

<details>
 <summary>

Stack trace</summary>

failed with "Cannot read property 'length' of undefined"
      Object.split (/source/list.es6:21:30)
    Object.space (/source/list.es6:68:21)
    manageIterStack (.../node_modules/postcss-for/index.js:28:38)
    .../node_modules/postcss-for/index.js:104:21
    /source/container.es6:268:28
    /source/container.es6:126:26
    Rule.each (/source/container.es6:94:22)
    Rule.walk (/source/container.es6:125:21)
    /source/container.es6:128:32
    Root.each (/source/container.es6:94:22)
    Root.walk (/source/container.es6:125:21)
    Root.walkAtRules (/source/container.es6:266:25)
    processOriginalLoops (.../node_modules/postcss-for/index.js:101:13)
    .../node_modules/postcss-for/index.js:112:9
    LazyResult.run (/source/lazy-result.es6:331:20)
    /source/lazy-result.es6:258:32
    LazyResult.asyncTick (/source/lazy-result.es6:256:13)
    /source/lazy-result.es6:270:22
    LazyResult.asyncTick (/source/lazy-result.es6:256:13)
    /source/lazy-result.es6:270:22
    LazyResult.asyncTick (/source/lazy-result.es6:256:13)
    processing.Promise.then._this2.processed (/source/lazy-result.es6:296:18)
    LazyResult.async (/source/lazy-result.es6:293:27)
    LazyResult.then (/source/lazy-result.es6:201:21)
    _combinedTickCallback (internal/process/next_tick.js:67:7)
    process._tickCallback (internal/process/next_tick.js:98:9)
</details>

**Comment by antyakushev** [comment]
@plesiecki Thank you! Please reopen if you'll still have any issues.
