### ISSUE TITLE
Why variable to cannot be used as a range parameter?

### ISSUE THREAD

**Issue by tunnckoCore** [antyakushev/postcss-for#3]
[ref #L13](https://github.com/antyakushev/postcss-for/blob/master/index.js#L13)
There's no logic for that. Why is this limit?

**Comment by antyakushev** [comment]
That's how PostCSS works. Postcss-for cannot be used after [postcss-simple-vars](https://github.com/postcss/postcss-simple-vars) since it will replace loop's `$i`. And being put before, postcss-for won't know the value variable stands for.

**Comment by antyakushev** [comment]
Have any ideas on solving this, without ruining postcss's modularity?

**Comment by tunnckoCore** [comment]
> since it will replace loop's $i

that's the idea, but hmm.. 
you have right, maybe it make more sense for `foreach` loop for collections.

**Comment by xori** [comment]
```
@for @i from 1 to $max-columns {
  .col-t-@i { width: calc(@i / $max-columns * 100%); }
}
```

IMO I think you could get away with making it a variable that `simple-var` doesn't recognize. I also think that it would make semantic sense as the variable `@i` is specific to this code block.

Now you can run this after `simple-vars` but before `calc` and you're golden.

**Update:**
for anyone who happens upon this with google like I did, I [forked](http://github.com/xori/postcss-for) this repo to enable the above syntax. I just needed it to just-work™
@antyakushev  maybe you'd consider a modified pull request to allow both the `$i` syntax or the `@i` syntax

**Comment by antyakushev** [comment]
@xori I assumed that [postcss-custom-properties](https://github.com/postcss/postcss-custom-properties), which is css future syntax, can be used for this. 
For now I'll mention both of the ways in the ReadMe to make googling easier.
