### ISSUE TITLE
Support for :root variables?

### ISSUE THREAD

**Issue by FalkoJoseph** [antyakushev/postcss-for#4]
```
@define-mixin column-generator {
    @for $i from 1 to calc(var(--columns) - 1) {
         &.with-$(i)col {
           width: (var(--one-column) * 1)px;
        }
    }
}
```

`@for $i from 1 to calc(var(--columns) - 1)` doesn't work. Anyone who knows why?

Is there a possibility to use the CSS4 variable spec alongside of simple-vars? Would be nice to stay as close to the CSS4 specs as possible. And this might solve the problem to use them as iterators.

**Comment by antyakushev** [comment]
@FalkoJoseph I believe that the current version of [postcss-calc](https://github.com/postcss/postcss-calc) is supposed to work in the CSS properties but not in the at-rules.

**Comment by FalkoJoseph** [comment]
Okay thanks for the update :+1:
